//modules to load:
const express = require('express');
const webpush = require('web-push');

const app = express();
//express framework manage basic route in server side 
//with app.get() , app.post() , app.delete() , ...

//NB VapidKeys can be generated by ./node_modules/.bin/web-push generate-vapid-keys


const publicVapidKey = "BG-THsg-ZuqK0np-UlWouA7i38Zhee-obwSKH2Dw7HYDwT6lIKi3l2STtz3TgVDvR0SSfSgWyf4QZk_XJVxsTW4";//process.env.PUBLIC_VAPID_KEY;
const privateVapidKey = "YH-vyz301BJlcu2XN0H13I8InZgUnbbkVBqRlMp-Xic";//process.env.PRIVATE_VAPID_KEY;

// Replace with your email
webpush.setVapidDetails('mailto:xy@zzz.com', publicVapidKey, privateVapidKey);

app.use(require('body-parser').json());

var gSubscription = null;

app.post('/registerUser', (req, res) => {
	const userRegistering = req.body;
	const userRegisteringAsJsonString = JSON.stringify(userRegistering);
	console.log("received userRegistering:"+ userRegisteringAsJsonString );
	res.status(200).json( userRegisteringAsJsonString );
});

app.post('/subscribe', (req, res) => {
  const subscription = req.body;
  gSubscription = subscription;
  res.status(201).json({});
  const payload = JSON.stringify({ title: 'first notification' , message : 'coucou' });

  console.log("received subscription:"+ JSON.stringify(subscription));

  webpush.sendNotification(subscription, payload).catch(error => {
    console.error(error.stack);
  });
  sendAnotherNotificationAfter5s();
});

function sendAnotherNotificationAfter5s(){
  var myIntObj = setTimeout(function () {
    //console.log("Hello at " + new Date());
	if(gSubscription!=null){
	  	const payload = JSON.stringify({ title: 'yet another notification' , message: "Hello at " + new Date() });
		webpush.sendNotification(gSubscription, payload).catch(error => {
           console.error(error.stack);
		});
	 }
    }, 5000);
}


app.use(require('express-static')('./')); //AFTER OTHER routes to serve static files !!!

app.listen(8282 , function () {
  console.log("simple express node server listening at 8282");
});